#!/bin/bash

echo "🚨 PYTHONANYWHERE DATABASE FIX 🚨"
echo "=================================="
echo ""

echo "Your site is loading but the database is empty."
echo "This script will create and populate the database with sample data."
echo ""

echo "📋 STEPS TO FIX YOUR DATABASE:"
echo ""
echo "1. Upload the fix_pythonanywhere_database.py file to PythonAnywhere"
echo "2. Go to PythonAnywhere Console tab"
echo "3. Run this command:"
echo "   python3.10 fix_pythonanywhere_database.py"
echo ""
echo "4. The script will create:"
echo "   - Main database: uploads/product_database.db"
echo "   - AGT_Bothell database: uploads/product_database_AGT_Bothell.db"
echo "   - Sample products with weight information"
echo ""
echo "5. Reload your web app after running the script"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "- ✅ Database will be created with proper structure"
echo "- ✅ Sample products will be added (including concentrate with weight)"
echo "- ✅ Your site will show products instead of being empty"
echo "- ✅ Weight field fixes will work with the new data"
echo ""

echo "🔧 ALTERNATIVE: Manual Database Creation"
echo "If the script doesn't work, you can also:"
echo "1. Go to PythonAnywhere Files tab"
echo "2. Create a folder called 'uploads'"
echo "3. Upload your existing database files (.db files) to the uploads folder"
echo "4. Make sure they're named: product_database.db and product_database_AGT_Bothell.db"
echo ""

echo "💡 TROUBLESHOOTING:"
echo "- Make sure the uploads directory exists"
echo "- Check file permissions on PythonAnywhere"
echo "- Verify the database files are in the correct location"
echo "- Check PythonAnywhere error logs if issues persist"
