
# Performance optimization flags for ultra-fast uploads
ENABLE_ULTRA_FAST_MODE = True
ENABLE_MINIMAL_PROCESSING = True
ENABLE_FAST_LOADING = True
ENABLE_LAZY_PROCESSING = False
ENABLE_BATCH_OPERATIONS = False
ENABLE_VECTORIZED_OPERATIONS = False
ENABLE_LINEAGE_PERSISTENCE = False
ENABLE_STRAIN_SIMILARITY_PROCESSING = False  # Disable for speed

# Ultra-fast constants
ULTRA_FAST_BATCH_SIZE = 500
ULTRA_FAST_MAX_ROWS = 5000
ULTRA_FAST_CACHE_SIZE = 64
